# Generated by Django 3.2 on 2022-05-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=2000),
        ),
    ]
