# Generated by Django 3.2 on 2022-05-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(height_field=620, upload_to='portfolio/images/'),
        ),
    ]
